services:
  headless:
    container_name: resonite-headless
    image: ghcr.io/voxelbonecloud/resonite-headless-docker:nofreetype 
    environment:
      # Set SKIP_STEAM_UPDATE to true to skip updating Resonite through Steam
      SKIP_STEAM_UPDATE: false
      STEAM_USER: "SomeSteamUsername"
      STEAM_PASS: "SomeSteamPassword"
      BETA_CODE: "ResoniteHeadlessKey"
    tty: true
    stdin_open: true
    user: "1000:1000"
    volumes:
    # Make sure you create a directory called "install" next to this compose file!
    # Resonite will be installed into this directory.
      - "./install:/home/container/install"