name: Docker auto updates

on:
  workflow_dispatch:
  schedule:
    - cron: '24 1 * * 1'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if base container update available
        id: check
        uses: lucacome/docker-image-update-checker@v3.0.1
        with:
          base-image: debian/trixie-slim
          image: ghcr.io/voxelbonecloud/resonite-headless-docker:main

      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.check.outputs.needs-updating == 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        if: steps.check.outputs.needs-updating == 'true'

      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ghcr.io/voxelbonecloud/headless-docker:${{ github.ref_name}}
        if: steps.check.outputs.needs-updating == 'true'
